Feat/sc-31614
OpenWebconcept/openpdd pull request #71
Opened 2024-12-24 15:03 UTC by hnccox-yard

Add a pronamic:cleanup command to invoke with crontab every day to remove fulfilled payments older than 5 days

2024-12-24 15:16 UTC, ictbeheer commented on htdocs/wp-content/themes/hollandskroon/src/Commands/PronamicIdealCommand.php
> +class PronamicIdealCommand
Een specifiekere naam (iets met cleanup erin) lijkt me wel handig.

2024-12-27 17:38 UTC, mvdhoek1 commented on htdocs/wp-content/themes/hollandskroon/src/Commands/PronamicIdealCommand.php
> +					WP_CLI::error('Failed to delete post with ID: ' . $payment->ID);
https://make.wordpress.org/cli/handbook/references/internal-api/wp-cli-error/

"Defaults to halting script execution", is dit wat je wilt? Wellicht is [deze](https://make.wordpress.org/cli/handbook/references/internal-api/wp-cli-warning/) meer op zijn plaats?

2024-12-27 17:38 UTC, mvdhoek1 commented on htdocs/wp-content/themes/hollandskroon/src/Commands/PronamicIdealCommand.php
> +				'posts_per_page' => $posts_per_page,
`$posts_per_page` -> `$postsPerPage`, geldt voor meerdere regels.

2024-12-27 17:38 UTC, mvdhoek1 commented on htdocs/wp-content/themes/hollandskroon/src/Commands/PronamicIdealCommand.php
> +			$payments = new \WP_Query(array(
`array()` -> `[]` (is heel erg mierenneuken dit)
Als je een WordPress plugin zou bouwen zou dit wel goed zijn btw.

2025-01-03 13:13 UTC, mvdhoek1 requested changes

2025-01-03 13:13 UTC, mvdhoek1 commented on htdocs/wp-content/themes/hollandskroon/src/Commands/PronamicIdealCleanupCommand.php
> +				'paged'          => 1,
1. `'paged'  => $paged,`

2025-01-03 13:13 UTC, mvdhoek1 commented on htdocs/wp-content/themes/hollandskroon/src/Commands/PronamicIdealCleanupCommand.php
> +			}
2. `$paged++;` anders blijf je op pagina 1 hangen en krijg je volgens mij een oneindige loop?

2025-01-03 13:13 UTC, mvdhoek1 commented on htdocs/wp-content/themes/hollandskroon/src/Commands/PronamicIdealCleanupCommand.php
> +				'posts_per_page' => $postsPerPage,
3. Of je skipt 1 en 2 en doet: `'posts_per_page' => -1,`
Dan kan de while loop ook weg.

2025-01-03 13:18 UTC, mvdhoek1 approved these changes

2025-01-03 13:33 UTC, dtakken requested changes

2025-01-03 13:33 UTC, dtakken commented on htdocs/wp-content/themes/hollandskroon/functions.php
> +	error_log('Error booting CommandServiceProvider: ' . $e->getMessage());
Dit is denk ik niet wat je wilt. Exceptions vang je alleen af wanneer je de error situatie kunt oplossen waarna je veilig door kunt. Ik zou zeggen: Laat die exception lekker over aan de exception handler van Fusion.

2025-01-06 09:05 UTC, dtakken commented on htdocs/wp-content/themes/hollandskroon/functions.php
> +	error_log('Error booting CommandServiceProvider: ' . $e->getMessage());
...en bij gebrek aan Fusion... aan de exception handler van WP.

2025-01-06 11:57 UTC, mvdhoek1 commented on htdocs/wp-content/themes/hollandskroon/functions.php
> +	error_log('Error booting CommandServiceProvider: ' . $e->getMessage());
Ik zou hem dit geval wel afvangen omdat anders de hele site eruit ligt. Aan de andere kant zie ik de serviceprovider in deze opzet geen exceptie gooien.

De afhandeling zou wel beter in serviceprovider passen.

Wellicht zit [hier](https://github.com/OpenWebconcept/openpdd/blob/master/htdocs/wp-content/themes/ggd-hollands-noorden/src/GGD/AFAS/AFAS.php#L15) nog een oplossing in en anders in de package/plugin die Dik aan het maken is?

2025-04-15 10:40 UTC, closed without merging